platform :ios, '9.0'

target 'Atlas' do
  use_frameworks!

  pod 'RxSwift'
  pod 'AWSCognitoIdentityProvider'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'RxRealm'
  pod 'RxDataSources'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'Dotzu'
  pod 'Whisper'
  pod 'SwiftyImage'
  pod 'RxGesture'
  pod 'RxSwiftExt'
  pod 'Auth0'
  pod 'SimpleKeychain'
  pod 'Lock'
  pod 'SDWebImage'
  pod 'DeckTransition'
  pod 'RxKeyboard'
  pod 'Charts'
  pod 'ChartsRealm'
  pod 'NMessenger'
  pod 'BouncyLayout'
  pod 'Pastel'
  pod 'Fakery'
  pod 'AvatarImageView'
  pod 'Kingfisher'
  pod 'Sourcery'
  pod 'Moya/RxSwift'
  pod 'RxRealm'
  pod 'JWTDecode'
  pod 'ObjectMapper'
  pod 'SkyFloatingLabelTextField'
end
