# https://github.com/fastlane/fastlane/tree/master/fastlane/docs

fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["FASTLANE_ITC_TEAM_ID"] = "111205916"
    ENV["FASTLANE_ITC_TEAM_NAME"] = "TRRN LLC"  # Redundant. Only here for documentation.
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: 'appstore') # more information: https://codesigning.guide   
    increment_build_number
    gym
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end


  after_all do |lane|
    # This block is called, only if the executed lane was successful

    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    clean_build_artifacts
    puts "\n(╯°□°）╯︵ ┻━┻\n".red
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
